name: seecovid
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  image_picker: 0.6.3
  material_design_icons_flutter: ^3.2.4096
  menu: ^0.1.4
  #country_code_picker: ^1.2.3
  #sim_info: ^0.1.1
  sqflite: ^1.2.0
  #flutter_image_compress: ^0.6.5+1
  #image_cropper: 1.2.0
  path_provider: any
  toast: any
  flutter_webview_plugin: 0.3.10+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  reflectable: any
  build_runner: any

  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  screen:
    path: lib/core/screen/
  flutter_launcher_icons: "^0.7.3"
  screen_generator: 
    path: lib/core/screen/screen_generator/
flutter:
  uses-material-design: true
  assets:
    - images/splash/
flutter_icons:
  android: true 
  ios: true
  image_path: "images/logo/karee.png"
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
